name: OpenMod.Unturned

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Unturned.yaml'
      - 'framework/**'
      - 'unityengine/**'
      - 'unturned/OpenMod.Unturned/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Unturned.yaml'
      - 'framework/**'
      - 'unityengine/**'
      - 'unturned/OpenMod.Unturned/**'

jobs:
  build:
    name: "OpenMod.Unturned Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      name: Setup .NET
      with:
        dotnet-version: 5.0.100
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: unturned/OpenMod.Unturned
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_repositories : ${{ secrets.Repositories }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
