name: OpenMod.Runtime

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Runtime.yaml'
      - 'framework/OpenMod.Runtime/**'
      - 'framework/OpenMod.Core/**'
      - 'framework/OpenMod.NuGet/**'
      - 'framework/OpenMod.API/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Runtime.yaml'
      - 'framework/OpenMod.Runtime/**'
      - 'framework/OpenMod.Core/**'
      - 'framework/OpenMod.NuGet/**'
      - 'framework/OpenMod.API/**'
jobs:
  build:
    name: "OpenMod.Runtime Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      name: Setup .NET
      with:
        dotnet-version: 5.0.100
    - uses: ././.github/actions/project-build
      id: project-build
      with:
        project_path: framework/OpenMod.Runtime
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_repositories : ${{ secrets.Repositories }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
